---
title: "Platform Belajar Ekonomi dan R"
format: html
editor: visual
---

Econ-R merupakan platform pembelajaran ekonomi komputasional yang memadukan teori, simulasi, serta visualisasi dengan memanfaatkan bahasa pemrograman R. Platform ini menyajikan materi ekonomi dasar dan pengenalan awal komputasi statistik yang dirancang khusus bagi pelajar tingkat menengah.

Pengembangan platform ini didasarkan pada pengalaman mengikuti program micromaster serta proses pembelajaran mandiri. R sendiri merupakan bahasa pemrograman berbasis *open-source* yang banyak digunakan untuk analisis statistik dan visualisasi data.

Melalui Econ-R, useRs diajak untuk belajar secara mandiri melalui pendekatan praktik langsung.Konsep-konsep ekonomi mikro akan dipahami dengan bantuan data sederhana yang diolah menggunakan R. Platform ini dapat menjadi pijakan awal sebelum melanjutkan ke tingkat pembelajaran lanjut, seperti program [Micromasters DEDP](https://micromasters.mit.edu/dedp/learner-resources/)

[Langkah awal](https://microeconr.netlify.app/lessons/lesson-1-introduction-to-economics-and-r)
