{
  "hash": "4fa1d5319b65b7641407ac4000e5b827",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Supply and Demand\"\nsubtitle: \"Lesson 2 - Economics with R\"\nauthor: \"Irfan Tri Raharjo\"\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-depth: 3\nexecute:\n  warning: false\n  message: false\n---\n\n# Penawaran dan Permintaan\n\nDi bagian ini, kita cari tahu konsep dasar yang mengatur semua harga di dunia: Permintaan (Demand) dan Penawaran (Supply). Selanjutnya, kita bakal coba visualisasikan dinamika ini pakai R.\n\n------------------------------------------------------------------------\n\n## Hukum Permintaan\n\nSekarang, pikirkan kopi susu favoritmu. Sampai akhir minggu lalu harga kopi susu itu masih 15 ribu, dan kamu beli stiap hari. Tapi, tiba-tiba mulai awal minggu ini harganya naik jadi 30 ribu. Kira-kira kamu masih beli sesering dulu enggak?\n\nKemungkinan besar enggak, kan? Mungkin kamu cuman akan beli awal bulan, atau cari alternatif yang lebih murah.\n\nInilah Hukum Permintaan: Kalau semua faktor lain tidak berubah, saat harga suatu barang naik, maka jumlah barang yang diminta akan turun. Sebalikanya, kalau harga turun, permintaan naik. Intinya: Hubungan antara harga dan permintaan itu terbalik. Inilah dasar mengapa harga di pasar bergerak.\n\n**Formula:**\n\n$$Qd = a - b*P$$\n\n## Bikin Kurva Permintaan di R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tentukan Fungsi Permintaannya\nprice <- seq(0, 100, by = 5)\nquantity_demanded <- 100 - 0.8 * price\n\n# Lanjut kita buat data frame\ndemand_data <- data.frame(\n  Price = price,\n  Quantity = quantity_demanded\n)\n\n# Baru Lanjut Plot Kurvanya\nlibrary(ggplot2)\nggplot(demand_data, aes(x = Quantity, y = Price)) +\n  geom_line(color = \"blue\", size = 1.5) +\n  labs(title = \"Demand Curve\",\n       x = \"Quantity Demanded\",\n       y = \"Price (Rp)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lesson-2-supply-and-demand_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n## Hukum Penawaran\n\nSekarang posisi kita adalah penjual atau produsen. Kamu adalah pemilik kedai kopi. Jika harga kopi susu lagi malah banget (30 ribu) kamu pasti semangat bangget buat bikin stok yang banyak, kalau perlu nambah jam operasional. Kenapa? Karena ada potensi Untung Gede.\n\nInilah Hukum Penawaran. Kalau semua faktor lain tidak berubah, saat harga suatu barang naik, jumlah barang yang ditawarkan juga akan bertambah. Intinya: Produsen itu semakin semangat menawarkan banyak barang ketika harganya sedang tinggi.\n\n**Formula:**\n\n$$Qs = c + d*P$$\n\n## Gabungkan Kurva Permintaan dan Penawaran\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tentukan Fungsi Permintaan & Penawaran\nprice <- seq(0, 100, by = 2)\nquantity_demanded <- 100 - 0.8 * price\nquantity_supplied <- -20 + 1.2 * price\n\n# Buat kombinasi data framenya\nmarket_data <- data.frame(\n  Price = price,\n  Demand = quantity_demanded,\n  Supply = quantity_supplied\n)\n\n# Cari Titik Keseimbangan\nequilibrium_price <- (100 + 20) / (0.8 + 1.2)\nequilibrium_quantity <- 100 - 0.8 * equilibrium_price\n\nprint(paste(\"Equilibrium Price:\", round(equilibrium_price, 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Equilibrium Price: 60\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste(\"Equilibrium Quantity:\", round(equilibrium_quantity, 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Equilibrium Quantity: 52\"\n```\n\n\n:::\n:::\n\n\n### Bikin Kurva Permintaan dan Penawaran\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Fungsi harga\nprice <- seq(0, 100, by = 2)\n\n# Fungsi permintaan & penawaran\ndemand <- 100 - 0.8 * price\nsupply <- -20 + 1.2 * price\n\n# Data frame pasar\nmarket_data <- data.frame(\n  Price = price,\n  Demand = demand,\n  Supply = supply\n)\n\n# cek 6 baris pertama\nhead(market_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Price Demand Supply\n1     0  100.0  -20.0\n2     2   98.4  -17.6\n3     4   96.8  -15.2\n4     6   95.2  -12.8\n5     8   93.6  -10.4\n6    10   92.0   -8.0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot kurva permintaan\n\nggplot(market_data) +\n  geom_line(aes(x = Demand, y = Price, color = \"Permintaan\")) +\n  geom_line(aes(x = Supply, y = Price, color = \"Penawaran\")) +\n  labs(\n    title = \"Kurva Permintaan dan Penawaran\",\n    x = \"Jumlah\",\n    y = \"Harga\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = c(0.9, 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](lesson-2-supply-and-demand_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nPermintaan dan penawaran membantu kita memahami bagaimana keputusan individu bertemu di pasar. Melalui kurva tersebut, kita bisa melihat bagaimana harga keseimbangan terbentuk, mengapa pasar cenderung menunju titik tertentu, dan bagaimana perubahan kondisi mempengaruhi hasil akhir.\nKonsep ini bisa menjadi fondasi untuk analisis kebijakan ekonomi. \n\n##Membuat Fungsi Permintaan\n\nPenasaran kan bagaimana fungsi permintaan seperti \n$$Qd = 1000 - 140*P$$\nbisa tiba-tiba muncul? Sini aku jelasin.\n\nMisal, seorang pelaku UMKM mencatat 30 kali transaksi penjualan tas sekolah. Penjualan ke-1 sampai ke-15, harga relatif stabil. Mulai penjualan ke-16, harga mulai dinaikkan (misal karena biaya bahan naik), maka:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed (123)\n\nn <- 30\nobs <- 1:n\n\n# Perhatikan, harga stabil lalu naik di observasi ke-16\nP <- c(\n  rep(80,15), #harga awal\n  seq(85, 120, length.out = 15) #harga naik bertahap\n)\n\n# Permintaan menurun + noise (perilaku konsumen tidak sempurna)\nQ <- 18000 - 100*P + rnorm(n, mean = 0, sd=300)\n\n# Buat dataframe data penjualan (datpj)\n\ndatpj <-data.frame(\n  obs = obs,\n  P=P,\n  Q=round(Q)\n  )\ndatpj\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   obs     P     Q\n1    1  80.0  9832\n2    2  80.0  9931\n3    3  80.0 10468\n4    4  80.0 10021\n5    5  80.0 10039\n6    6  80.0 10515\n7    7  80.0 10138\n8    8  80.0  9620\n9    9  80.0  9794\n10  10  80.0  9866\n11  11  80.0 10367\n12  12  80.0 10108\n13  13  80.0 10120\n14  14  80.0 10033\n15  15  80.0  9833\n16  16  85.0 10036\n17  17  87.5  9399\n18  18  90.0  8410\n19  19  92.5  8960\n20  20  95.0  8358\n21  21  97.5  7930\n22  22 100.0  7935\n23  23 102.5  7442\n24  24 105.0  7281\n25  25 107.5  7062\n26  26 110.0  6494\n27  27 112.5  7001\n28  28 115.0  6546\n29  29 117.5  5909\n30  30 120.0  6376\n```\n\n\n:::\n:::\n\n\nSetelah kita dapatkan data, selanjutnya kita periksa visualisasi datanya\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(datpj, aes(x=P, y=Q)) +\n  geom_point(size=2) +\n  geom_vline(xintercept = P[16], linetype = \"dashed\") +\n  labs(\n    title = \"Data Penjualan UMKM\",\n    subtitle = \"Harga naik mulai observasi ke-16\",\n    x = \"Harga (ribu rupiah)\",\n    y = \"Jumlah Terjual\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lesson-2-supply-and-demand_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\nMelalui visualisasi kita bisa lihat secara jelas ya bagaimana pola datanya. Lanjut, bagian terpenting untuk menjawab pertanyaan awal bagaimana fungsi permintaannya?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_permint <- lm(Q ~ P, data = datpj)\n\nsummary(model_permint)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Q ~ P, data = datpj)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-581.31 -203.14  -13.31  160.33  522.65 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 18388.020    362.997   50.66   <2e-16 ***\nP            -104.408      3.935  -26.54   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 293 on 28 degrees of freedom\nMultiple R-squared:  0.9618,\tAdjusted R-squared:  0.9604 \nF-statistic: 704.2 on 1 and 28 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\nBerdasarkan formula diatas, kita dapati hasil sebagai berikut:\n\nPerhatikan nilai intercept dan P\n\nQ = 18388 - 104*P\nQ = 18388 - 104P\n\nIni adalah fungsi permintaan linear. Apakah kalian bisa mengartikan nilai koefisien dari fungsi tersebut?\n\n------------------------------------------------------------------------\n",
    "supporting": [
      "lesson-2-supply-and-demand_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}